<a href="https://colab.research.google.com/github/ginttone/multi_deeplearning/blob/master/NLP/Seq2Seq_preprocess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Chatboot , Translation

## Sequence-to-Sequence


LSTM : 처음 나온 이유는 원래 번역을 위해서였다. 기존의 Dense Layers가 긴 문장을 처리하기 어려운 레이어였다. 

[RNN](https://wikidocs.net/22886)

`↓`

[LSTM , GRU](https://excelsior-cjh.tistory.com/185) 


`↓`

[seq 2 seq](https://wikidocs.net/24996)

`↓`

[Self Attention](https://wikidocs.net/31379)

`↓`

[BERT](https://wikidocs.net/115055)
GPT3

인풋 스트링 넣고, 아웃풋 스트링 지정해주면 만들어 진다.

In [ ]:
!python -m pip install konlpy

./drive/MyDrive/Multi_test_deeplearning/vocabulary.txt

./drive/MyDrive/Multi_test_deeplearning/ChatBotData.csv_short

./drive/MyDrive/Multi_test_deeplearning/preprocess.py

In [4]:
# from preprocess import *
import preprocess as pp

In [5]:
path_csv = './drive/MyDrive/Multi_test_deeplearning/ChatBotData.csv_short'

In [6]:
inputs, outputs= pp.load_data(path_csv)

In [7]:
type(inputs), type(outputs)

(list, list)

In [8]:
inputs[7], outputs[7]

('가스불 켜놓고 나온거 같아', '빨리 집에 돌아가서 끄고 나오세요.')

In [9]:
inputs[10], outputs[10]

('남자친구 교회 데려가고 싶어', '마음을 열 때까지 설득해보세요.')

In [10]:
len(inputs), len(outputs)

(20, 20)

In [11]:
path_vocab = './drive/MyDrive/Multi_test_deeplearning/vocabulary.txt'

In [12]:
char2idx,idx2char,vocab_size = pp.load_vocabulary(path_csv, path_vocab, tokenize_as_morph=False)
type(char2idx),type(idx2char),type(vocab_size)

(dict, dict, int)

(char2idx) 단어 숫자

(idx2char) 숫자 단어

(vocab_size) 단어 사이즈

In [13]:
print(char2idx)
print(idx2char)
print(vocab_size)

{'<PAD>': 0, '<SOS>': 1, '<END>': 2, '<UNK>': 3, '운동': 4, '가상화폐': 5, '나온거': 6, '있어도': 7, '적당히': 8, '오늘': 9, '것': 10, '좋을': 11, '돈은': 12, '운동만': 13, '걸리겠어': 14, '훈훈해': 15, '달에는': 16, '빨리': 17, '전생에': 18, '데려가고': 19, '가난한': 20, '혼자를': 21, '생일인데': 22, '너무': 23, '쫄딱': 24, '때까지': 25, '같아': 26, '뭐가': 27, '생각해보세요': 28, '켜놓고': 29, '자의': 30, '좀': 31, '거예요': 32, '잘생겼어': 33, '운동을': 34, '좋다': 35, '구하셨나요': 36, '그': 37, '사세요': 38, '빠를수록': 39, '선물로': 40, '가끔': 41, '필요했던': 42, '같아요': 43, '사람도': 44, '갔어': 45, '평소에': 46, '마세요': 47, '식혀주세요': 48, '새출발': 49, '해보세요': 50, '즐기세요': 51, '따라': 52, '끄고': 53, '좋을까': 54, '승진': 55, '결단은': 56, '어서': 57, '들어올': 58, '나갔어': 59, '바빠': 60, '열': 61, '망함': 62, '궁금해': 63, '거짓말': 64, '남자친구가': 65, '땀을': 66, '가스불': 67, '돌아가서': 68, '게': 69, '남자친구': 70, '비싼데': 71, '나오세요': 72, '따뜻하게': 73, '나': 74, '좋아요': 75, '많이': 76, '가스비': 77, '집착하지': 78, '땀난다': 79, '뭐하는지': 80, '다시': 81, '더': 82, '해': 83, '보인다': 84, '하세요': 85, '나라를': 86, '필요한': 87, '마음을': 88, '나왔다': 89, '잊고': 90, '안': 91, '믿어줘':

In [28]:
# inputs

idx_inputs, input_seq_len = pp.enc_processing(inputs, char2idx)
type(idx_inputs), len(input_seq_len) 

(numpy.ndarray, 20)

In [29]:
idx_inputs[3:5]

array([[ 20,  30, 107,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 93,   7,  79,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [30]:
# outputs

idx_outputs, outputs_seq_len = pp.dec_output_processing(outputs, char2idx)
type(idx_outputs), outputs_seq_len

(numpy.ndarray, [5, 5, 3, 5, 3, 5, 6, 6, 5, 3, 5, 4, 5, 7, 4, 4, 4, 4, 4, 4])

In [31]:
idx_outputs[3:5]

array([[ 1, 12, 81, 58, 32,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1, 66, 48,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [32]:
# target

idx_targets = pp.dec_target_processing(outputs, char2idx)
type(idx_targets), len(idx_targets)

(numpy.ndarray, 20)

In [33]:
idx_targets[3:5]

array([[12, 81, 58, 32,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [66, 48,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0]])

## Numpy로 떨궈서 사용하기

행열이 숫자일 경우 , pandas로 떨궈서 사용하는 것 보다 빠르게 사용이 가능하다. 

In [39]:
import numpy as np

In [43]:
!ls ./drive/MyDrive/Multi_test_deeplearning/train_inputs.npy

./drive/MyDrive/Multi_test_deeplearning/train_inputs.npy


In [40]:
# np.save(open('./drive/MyDrive/Multi_test_deeplearning/train_inputs.npy','wb'),idx_inputs)

In [45]:
# np.save(open('./drive/MyDrive/Multi_test_deeplearning/train_outputs.npy','wb'),idx_outputs)

In [46]:
# np.save(open('./drive/MyDrive/Multi_test_deeplearning/train_targets.npy','wb'),idx_targets)

In [53]:
data_configs = dict()

In [54]:
data_configs['char2idx'] = char2idx
data_configs['idx2char'] = idx2char
data_configs['vocab_size'] = vocab_size

In [55]:
data_configs['pad_symbol'] = '<PAD>'
data_configs['std_symbol'] = '<STD>'
data_configs['end_symbol'] = '<END>'
data_configs['unk_symbol'] = '<UNK>'

In [56]:
# pp.json.dump(data_configs, open('./drive/MyDrive/Multi_test_deeplearning/data_configs.json','w'))