<a href="https://colab.research.google.com/github/ginttone/multi_deeplearning/blob/master/dff_sigmoid_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow 

## activation > sigmoid

```
a = tf.constant([-20, -1.0, 0.0, 1.0, 20], dtype = tf.float32)
b = tf.keras.activations.sigmoid(a)
b.numpy()
```

In [1]:
import tensorflow as tf

constant 는 상수를 선언하는 방법

In [9]:
a = tf.constant([4.0, 1.0, 3.0], dtype = tf.float32)
a , type(a)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 1., 3.], dtype=float32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [10]:
b = tf.keras.activations.sigmoid(a)
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)>

In [11]:
b.numpy()

array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)

## activation > softmax

```
inputs = tf.random.normal(shape=(32, 10))
outputs = tf.keras.activations.softmax(inputs)
tf.reduce_sum(outputs[0, :])
```

In [19]:
inputs = tf.random.normal(shape=(1, 3))
inputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1.9198573 , 0.24816824, 0.8690127 ]], dtype=float32)>

In [20]:
outputs = tf.keras.activations.softmax(inputs)
outputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.6503762 , 0.12222479, 0.22739905]], dtype=float32)>

In [21]:
outputs.numpy()

array([[0.6503762 , 0.12222479, 0.22739905]], dtype=float32)

소프트 맥스는 노드에서 의견을 내서 맨 마지막 아웃풋에 들어가면 해당 부분이 아무리 많은 의견이 들어와도 0과 1안으로 수렴시킨다.

그래서 우리는 1에가장 가까운 결과값을 찾으면 된다.