<a href="https://colab.research.google.com/github/ginttone/multi_deeplearning/blob/master/iris_Deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 데이터 가져오기(sklearn -> iris)

In [1]:
from sklearn import datasets

iris 데이터가 cm로 동일하기 때문에 스케일링 할 필요 없다


iris.feaure_names  (각 컬럼 네임)
```
['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']
```

iris.data와 target을 쓸거다

In [2]:
iris = datasets.load_iris()

In [3]:
import pandas as pd

In [4]:
df_iris = pd.DataFrame(iris.data)

In [5]:
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


##  DB에 넣기

In [6]:
import sqlite3

In [7]:
connect = sqlite3.connect('./db.sqlite3')

In [23]:
df_iris.to_sql('iris_resource', connect, if_exists='replace' , index=False)

In [24]:
df_load = pd.read_sql_query('select * from iris_resource', connect)

df_load.head(4)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2

In [25]:
x_data = df_load.to_numpy()

In [26]:
x_data.shape

(150, 4)

In [27]:
y_data = iris.target

In [28]:
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
import numpy as np
np.unique(y_data)

array([0, 1, 2])

(스플릿 단계 생략)

## 교육단계 

데이터 통째로 딥러닝에 넣기

### 모델만들기

In [30]:
import tensorflow as tf

In [31]:
model = tf.keras.Sequential()

In [32]:
model.add(tf.keras.Input(shape =(4,)))

In [33]:
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(24, activation='relu'))

In [34]:
model.add(tf.keras.layers.Dense(3,activation='softmax'))

In [35]:
model.compile(optimizer='adam', loss='mse', metrics=['acc'])

In [36]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 64)                320       
_________________________________________________________________
dense_4 (Dense)              (None, 24)                1560      
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 75        
Total params: 1,955
Trainable params: 1,955
Non-trainable params: 0
_________________________________________________________________


### 학습시키기

validation_split 쏠림 현상이 있을 수 있으니 다른데이터랑 비교하는 것 

In [37]:
model.fit(x_data, y_data, epochs=50, validation_split=0.3)

Epoch 1/50
4/4 [==============================] - 1s 107ms/step - loss: 0.4109 - acc: 0.5333 - val_loss: 2.7820 - val_acc: 0.0000e+00
Epoch 2/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3990 - acc: 0.7810 - val_loss: 2.7800 - val_acc: 0.9778
Epoch 3/50
4/4 [==============================] - 0s 10ms/step - loss: 0.4005 - acc: 0.5143 - val_loss: 2.7818 - val_acc: 0.9778
Epoch 4/50
4/4 [==============================] - 0s 8ms/step - loss: 0.3999 - acc: 0.4952 - val_loss: 2.7795 - val_acc: 0.9778
Epoch 5/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3977 - acc: 0.5048 - val_loss: 2.7783 - val_acc: 0.5778
Epoch 6/50
4/4 [==============================] - 0s 10ms/step - loss: 0.3972 - acc: 0.7429 - val_loss: 2.7792 - val_acc: 0.1111
Epoch 7/50
4/4 [==============================] - 0s 11ms/step - loss: 0.3976 - acc: 0.4857 - val_loss: 2.7787 - val_acc: 0.2222
Epoch 8/50
4/4 [==============================] - 0s 11ms/step - loss: 0.3973 - acc: 0.5524 - v

### 검증

In [38]:
model.evaluate(x_data, y_data)

5/5 [==============================] - 0s 2ms/step - loss: 1.1112 - acc: 0.4667


[1.1112420558929443, 0.46666666865348816]

## 서비스 단계

In [39]:
x_data[25] , y_data[25]

(array([5. , 3. , 1.6, 0.2]), 0)

In [40]:
pred = model.predict([[5. , 3. , 1.6, 0.2]])
pred

array([[0.3293799 , 0.34417996, 0.32644016]], dtype=float32)

In [41]:
import numpy as np
np.argmax(pred)

1