<a href="https://colab.research.google.com/github/ginttone/multi_deeplearning/blob/master/iris_Deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 데이터 가져오기(sklearn -> iris)

In [1]:
from sklearn import datasets

iris 데이터가 cm로 동일하기 때문에 스케일링 할 필요 없다


iris.feaure_names  (각 컬럼 네임)
```
['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']
```

iris.data와 target을 쓸거다

In [2]:
iris = datasets.load_iris()

In [3]:
import pandas as pd

In [4]:
df_iris = pd.DataFrame(iris.data)

In [5]:
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


##  DB에 넣기

In [6]:
import sqlite3

In [7]:
connect = sqlite3.connect('./db.sqlite3')

In [8]:
df_iris.to_sql('iris_resource', connect, if_exists='append' , index=False)

In [9]:
df_load = pd.read_sql_query('select * from iris_resource', connect)

df_load.head(4)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2

In [10]:
x_data = df_load.to_numpy()

In [11]:
x_data.shape

(600, 4)

In [12]:
y_data = iris.target

In [13]:
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
import numpy as np
np.unique(y_data)

array([0, 1, 2])

(스플릿 단계 생략)

## 교육단계 

데이터 통째로 딥러닝에 넣기

### 모델만들기

In [15]:
import tensorflow as tf

In [16]:
model = tf.keras.Sequential()

In [17]:
model.add(tf.keras.Input(shape =(4,)))

In [18]:
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(24, activation='relu'))

In [19]:
model.add(tf.keras.layers.Dense(3,activation='softmax'))

In [20]:
model.compile(optimizer='adam', loss='mse', metrics=['acc'])

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                320       
_________________________________________________________________
dense_1 (Dense)              (None, 24)                1560      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 75        
Total params: 1,955
Trainable params: 1,955
Non-trainable params: 0
_________________________________________________________________


### 학습시키기

validation_split 쏠림 현상이 있을 수 있으니 다른데이터랑 비교하는 것 

In [27]:
model.fit(x_data, y_data, epochs=50, validation_split=0.3)

ValueError: ignored

### 검증

In [ ]:
model.evaluate(x_data, y_data)

## 서비스 단계

In [23]:
x_data[25] , y_data[25]

(array([5. , 3. , 1.6, 0.2]), 0)

In [25]:
pred = model.predict([[5. , 3. , 1.6, 0.2]])
pred

array([[0.4501303 , 0.2897314 , 0.26013824]], dtype=float32)

In [26]:
import numpy as np
np.argmax(pred)

0