<a href="https://colab.research.google.com/github/ginttone/multi_deeplearning/blob/master/multi_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
x_data = [[0,0],
          [1,0],
          [0,1],
          [1,1]]
y_data = [[0],
          [1],
          [1],
          [1]]

type(x_data),type(y_data)

(list, list)

## 넘파이 어레이로 바꿈

In [3]:
import numpy as np

In [4]:
x_train = np.array(x_data)
y_train = np.array(y_data)
x_train.shape , y_train.shape

((4, 2), (4, 1))

## 딥러닝에 넣어주는 작업(모델만들기)

**create model**

multi perceptron(layer가 한 개 이상)의 사용

solve XOR model(XOR 해결하기) 

In [5]:
model = tf.keras.models.Sequential()

In [6]:
model.add(tf.keras.Input(shape=(2,)))  # input layer 1차원

In [7]:
model.add(tf.keras.layers.Dense(2,activation='sigmoid'))

# model.add(tf.keras.layers.Dense(128,activation='sigmoid')) # 기능 layer
# model.add(tf.keras.layers.Dense(128,activation='sigmoid'))

엑티베이션 펑션(활성화 함수) 사용

dense자체는 regrassin 이어서 activation을 넣어줘야한다

In [8]:
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))# output layer

metrics=['acc'] 정확도 측정할 때 필요 

In [9]:
model.compile(optimizer='sgd', loss='mse', metrics=['acc'])

In [10]:
# tf.keras.utils.plot_model(model, show_shapes=True)

기능 layer부분 개수를 늘리기

In [11]:
model.fit(x_train, y_train, epochs=100) 

Epoch 1/100
1/1 [==============================] - 1s 645ms/step - loss: 0.1917 - acc: 0.7500
Epoch 2/100
1/1 [==============================] - 0s 10ms/step - loss: 0.1916 - acc: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 0.1915 - acc: 0.7500
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 0.1915 - acc: 0.7500
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 0.1914 - acc: 0.7500
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 0.1913 - acc: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 19ms/step - loss: 0.1913 - acc: 0.7500
Epoch 8/100
1/1 [==============================] - 0s 7ms/step - loss: 0.1912 - acc: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 4ms/step - loss: 0.1912 - acc: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 0.1911 - acc: 0.7500
Epoch 11/100
1/1 [==============================] - 0s 5ms/step - loss: 0.1

## loss 체크 : 숫자가 낮을 수록 좋다

기능 레이어 Dense 2 로 변화 체크

epochs = 100 한 번 loss: 0.2202

기능 레이어 Dense 32 늘리고 변화 체크 

epochs = 100 한 번 loss: 0.1904

기능 레이어 Dense 132 늘리고 변화 체크

epochs = 100 한 번 loss: 0.1848

기능 레이어 Dense 128*2 하고 변화 체크

epochs = 100 한 번 loss: 0.1865 array = 0.7413647

**결론**: 성능을 높이려면 

Dense 높이거나, 

기능레이어 여러번(2번) 쌓거나, 

에폭 횟수를 늘리면 된다


In [12]:
model.predict([[0,1]])

array([[0.6595406]], dtype=float32)

## evaluate() 정확도 : 숫자가 높을 수록 좋다

sklearn이랑 동일한 아이 

In [13]:
model.evaluate(x_train, y_train)

1/1 [==============================] - 0s 128ms/step - loss: 0.1862 - acc: 0.7500


[0.18622949719429016, 0.75]

In [14]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[ 0.20227471, -0.7743279 ],
        [ 0.75712776,  0.7813313 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(2,) dtype=float32, numpy=array([ 0.00837669, -0.00055063], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[ 0.9422685 ],
        [-0.04573388]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.04947107], dtype=float32)>]

[구조확인](https://playground.tensorflow.org/
)

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 6         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
